version: '3.6'
services:
  web:
    image: nginx:alpine
    ports:
      - "1002:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - paterns
  php:
    build:
      context: .
    restart: always
    volumes:
      - ./:/var/www/html
    networks:
      - paterns
    depends_on:
      - web
      - database
  database:
    image: mysql:5.7
    ports:
      - "3308:3308"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
      - paterns_data:/var/lib/mysql
    networks:
      - paterns
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "2000:80"
    depends_on:
      - database
    links:
      - "database:db"
    networks:
      - paterns
networks:
  paterns:
    name: paterns
    driver: bridge
volumes:
  paterns_data:
    driver: local
